import type { INodePropertyOptions } from 'n8n-workflow';

/**
 * The full list of events Billomat can send, taken from the values it puts into the
 * X-Billomat-Webhook-Event header. Estimates are called offers in the API.
 */
export const BILLOMAT_EVENT_OPTIONS: INodePropertyOptions[] = [
	{ name: 'Article Created', value: 'article.create' },
	{ name: 'Article Deleted', value: 'article.delete' },
	{ name: 'Article Property Created', value: 'article_property.create' },
	{ name: 'Article Property Deleted', value: 'article_property.delete' },
	{ name: 'Article Property Updated', value: 'article_property.update' },
	{ name: 'Article Property Value Updated', value: 'article_property_value.update' },
	{ name: 'Article Updated', value: 'article.update' },
	{ name: 'Client Created', value: 'client.create' },
	{ name: 'Client Deleted', value: 'client.delete' },
	{ name: 'Client Property Created', value: 'client_property.create' },
	{ name: 'Client Property Deleted', value: 'client_property.delete' },
	{ name: 'Client Property Updated', value: 'client_property.update' },
	{ name: 'Client Property Value Updated', value: 'client_property_value.update' },
	{ name: 'Client Updated', value: 'client.update' },
	{ name: 'Confirmation Comment Created', value: 'confirmation_comment.create' },
	{ name: 'Confirmation Comment Deleted', value: 'confirmation_comment.delete' },
	{ name: 'Confirmation Created', value: 'confirmation.create' },
	{ name: 'Confirmation Deleted', value: 'confirmation.delete' },
	{ name: 'Confirmation Sent', value: 'confirmation.send' },
	{ name: 'Confirmation Status Changed', value: 'confirmation.status' },
	{ name: 'Confirmation Updated', value: 'confirmation.update' },
	{ name: 'Contact Created', value: 'contact.create' },
	{ name: 'Contact Deleted', value: 'contact.delete' },
	{ name: 'Contact Updated', value: 'contact.update' },
	{ name: 'Credit Note Comment Created', value: 'credit_note_comment.create' },
	{ name: 'Credit Note Comment Deleted', value: 'credit_note_comment.delete' },
	{ name: 'Credit Note Created', value: 'credit_note.create' },
	{ name: 'Credit Note Deleted', value: 'credit_note.delete' },
	{ name: 'Credit Note Payment Created', value: 'credit_note_payment.create' },
	{ name: 'Credit Note Payment Deleted', value: 'credit_note_payment.delete' },
	{ name: 'Credit Note Sent', value: 'credit_note.send' },
	{ name: 'Credit Note Status Changed', value: 'credit_note.status' },
	{ name: 'Credit Note Updated', value: 'credit_note.update' },
	{ name: 'Delivery Note Comment Created', value: 'delivery_note_comment.create' },
	{ name: 'Delivery Note Comment Deleted', value: 'delivery_note_comment.delete' },
	{ name: 'Delivery Note Created', value: 'delivery_note.create' },
	{ name: 'Delivery Note Deleted', value: 'delivery_note.delete' },
	{ name: 'Delivery Note Sent', value: 'delivery_note.send' },
	{ name: 'Delivery Note Status Changed', value: 'delivery_note.status' },
	{ name: 'Delivery Note Updated', value: 'delivery_note.update' },
	{ name: 'Estimate Comment Created', value: 'offer_comment.create' },
	{ name: 'Estimate Comment Deleted', value: 'offer_comment.delete' },
	{ name: 'Estimate Created', value: 'offer.create' },
	{ name: 'Estimate Deleted', value: 'offer.delete' },
	{ name: 'Estimate Sent', value: 'offer.send' },
	{ name: 'Estimate Status Changed', value: 'offer.status' },
	{ name: 'Estimate Updated', value: 'offer.update' },
	{ name: 'Incoming Comment Created', value: 'incoming_comment.create' },
	{ name: 'Incoming Comment Deleted', value: 'incoming_comment.delete' },
	{ name: 'Incoming Created', value: 'incoming.create' },
	{ name: 'Incoming Deleted', value: 'incoming.delete' },
	{ name: 'Incoming Payment Created', value: 'incoming_payment.create' },
	{ name: 'Incoming Payment Deleted', value: 'incoming_payment.delete' },
	{ name: 'Incoming Property Created', value: 'incoming_property.create' },
	{ name: 'Incoming Property Deleted', value: 'incoming_property.delete' },
	{ name: 'Incoming Property Updated', value: 'incoming_property.update' },
	{ name: 'Incoming Property Value Updated', value: 'incoming_property_value.update' },
	{ name: 'Incoming Status Changed', value: 'incoming.status' },
	{ name: 'Incoming Updated', value: 'incoming.update' },
	{ name: 'Invoice Comment Created', value: 'invoice_comment.create' },
	{ name: 'Invoice Comment Deleted', value: 'invoice_comment.delete' },
	{ name: 'Invoice Created', value: 'invoice.create' },
	{ name: 'Invoice Deleted', value: 'invoice.delete' },
	{ name: 'Invoice Payment Created', value: 'invoice_payment.create' },
	{ name: 'Invoice Payment Deleted', value: 'invoice_payment.delete' },
	{ name: 'Invoice Sent', value: 'invoice.send' },
	{ name: 'Invoice Status Changed', value: 'invoice.status' },
	{ name: 'Invoice Updated', value: 'invoice.update' },
	{ name: 'Recurring Created', value: 'recurring.create' },
	{ name: 'Recurring Deleted', value: 'recurring.delete' },
	{ name: 'Recurring Updated', value: 'recurring.update' },
	{ name: 'Reminder Created', value: 'reminder.create' },
	{ name: 'Reminder Deleted', value: 'reminder.delete' },
	{ name: 'Reminder Sent', value: 'reminder.send' },
	{ name: 'Reminder Status Changed', value: 'reminder.status' },
	{ name: 'Reminder Updated', value: 'reminder.update' },
	{ name: 'Supplier Created', value: 'supplier.create' },
	{ name: 'Supplier Deleted', value: 'supplier.delete' },
	{ name: 'Supplier Property Created', value: 'supplier_property.create' },
	{ name: 'Supplier Property Deleted', value: 'supplier_property.delete' },
	{ name: 'Supplier Property Updated', value: 'supplier_property.update' },
	{ name: 'Supplier Property Value Updated', value: 'supplier_property_value.update' },
	{ name: 'Supplier Updated', value: 'supplier.update' },
];
