import type { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

import {
	NET_GROSS_OPTIONS,
	PAYMENT_TYPE_FILTER_OPTIONS,
	PAYMENT_TYPE_OPTIONS,
	SUPPLY_DATE_TYPE_OPTIONS,
	additionalFields,
	filterFields,
	idField,
	orderByField,
	paginationFields,
	tagsFilterField,
} from './SharedFields';
import { documentLineItemsField } from './DocumentFields';

const resource = 'recurring';

const CYCLE_OPTIONS: INodePropertyOptions[] = [
	{ name: 'Daily', value: 'DAILY' },
	{ name: 'Monthly', value: 'MONTHLY' },
	{ name: 'Weekly', value: 'WEEKLY' },
	{ name: 'Yearly', value: 'YEARLY' },
];

export const recurringOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [resource],
			},
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a recurring invoice',
				action: 'Create a recurring invoice',
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a recurring invoice including its items',
				action: 'Delete a recurring invoice',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get a recurring invoice',
				action: 'Get a recurring invoice',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many recurring invoices',
				action: 'Get many recurring invoices',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a recurring invoice',
				action: 'Update a recurring invoice',
			},
		],
		default: 'create',
	},
];

const recurringFieldOptions: INodeProperties[] = [
	{
		displayName: 'Action',
		name: 'action',
		type: 'options',
		options: [
			{ name: 'Complete', value: 'COMPLETE' },
			{ name: 'Create', value: 'CREATE' },
			{ name: 'Email', value: 'EMAIL' },
			{ name: 'Mail', value: 'MAIL' },
		],
		default: 'CREATE',
		description:
			'What Billomat does when the recurring fires. Create leaves a draft, Complete also completes it, and Email or Mail additionally send it.',
	},
	{
		displayName: 'Confirmation ID',
		name: 'confirmation_id',
		type: 'string',
		default: '',
		description: 'ID of the confirmation the recurring was created from',
	},
	{
		displayName: 'Contact ID',
		name: 'contact_id',
		type: 'string',
		default: '',
	},
	{
		displayName: 'Currency Code',
		name: 'currency_code',
		type: 'string',
		default: '',
		placeholder: 'EUR',
		description: 'ISO currency code. Defaults to the account currency.',
	},
	{
		displayName: 'Cycle',
		name: 'cycle',
		type: 'options',
		options: CYCLE_OPTIONS,
		default: 'MONTHLY',
		description: 'Interval at which the recurring fires',
	},
	{
		displayName: 'Cycle Number',
		name: 'cycle_number',
		type: 'number',
		default: 1,
		description: 'Number of intervals, for example 3 together with Monthly for every 3 months',
	},
	{
		displayName: 'Discount Days',
		name: 'discount_days',
		type: 'number',
		default: 0,
		description: 'Cash discount days',
	},
	{
		displayName: 'Discount Rate',
		name: 'discount_rate',
		type: 'number',
		default: 0,
		description: 'Cash discount in percent',
	},
	{
		displayName: 'Due Days',
		name: 'due_days',
		type: 'number',
		default: 0,
	},
	{
		displayName: 'Email BCC',
		name: 'email_bcc',
		type: 'boolean',
		default: false,
		description: 'Whether to put the sender in BCC',
	},
	{
		displayName: 'Email File Name',
		name: 'email_filename',
		type: 'string',
		default: '',
		description: 'File name of the invoice when sending by email',
	},
	{
		displayName: 'Email Message',
		name: 'email_message',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
	},
	{
		displayName: 'Email Sender',
		name: 'email_sender',
		type: 'string',
		default: '',
		placeholder: 'name@email.com',
	},
	{
		displayName: 'Email Subject',
		name: 'email_subject',
		type: 'string',
		default: '',
	},
	{
		displayName: 'Email Template ID',
		name: 'email_template_id',
		type: 'string',
		default: '',
	},
	{
		displayName: 'End Date',
		name: 'end_date',
		type: 'dateTime',
		default: '',
	},
	{
		displayName: 'Free Text ID',
		name: 'free_text_id',
		type: 'string',
		default: '',
		description: 'ID of the free text used to preset title, label, intro and note',
	},
	{
		displayName: 'Hour',
		name: 'hour',
		type: 'number',
		default: 2,
		description: 'Time of day the recurring fires, as an hour between 0 and 23',
	},
	{
		displayName: 'Intro',
		name: 'intro',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
	},
	{
		displayName: 'Label',
		name: 'label',
		type: 'string',
		default: '',
		description: 'Label text describing the project',
	},
	{
		displayName: 'Letter Color',
		name: 'letter_color',
		type: 'boolean',
		default: false,
		description: 'Whether to use color printing when sending by letter',
	},
	{
		displayName: 'Letter Duplex',
		name: 'letter_duplex',
		type: 'boolean',
		default: true,
		description: 'Whether to use duplex printing when sending by letter',
	},
	{
		displayName: 'Letter Paper Weight',
		name: 'letter_paper_weight',
		type: 'options',
		options: [
			{ name: '80 G', value: 80 },
			{ name: '90 G', value: 90 },
		],
		default: 90,
		description: 'Paper weight in grams when sending by letter',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		description: 'Name of the recurring',
	},
	{
		displayName: 'Net or Gross',
		name: 'net_gross',
		type: 'options',
		options: NET_GROSS_OPTIONS,
		default: 'NET',
		description: 'Whether the line item prices are net or gross',
	},
	{
		displayName: 'Next Creation Date',
		name: 'next_creation_date',
		type: 'dateTime',
		default: '',
		description: 'Date of the next creation. Defaults to the start date.',
	},
	{
		displayName: 'Note',
		name: 'note',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
	},
	{
		displayName: 'Offer ID',
		name: 'offer_id',
		type: 'string',
		default: '',
		description: 'ID of the estimate the recurring was created from',
	},
	{
		displayName: 'Payment Types',
		name: 'payment_types',
		type: 'multiOptions',
		options: PAYMENT_TYPE_OPTIONS,
		default: [],
	},
	{
		displayName: 'Quote',
		name: 'quote',
		type: 'number',
		default: 1,
		description: 'Currency quote used to convert into the account currency',
	},
	{
		displayName: 'Reduction',
		name: 'reduction',
		type: 'string',
		default: '',
		placeholder: '10%',
		description: 'Reduction as an absolute amount or a percentage, for example 10 or 10%',
	},
	{
		displayName: 'Start Date',
		name: 'start_date',
		type: 'dateTime',
		default: '',
		description: 'Start date. Defaults to tomorrow.',
	},
	{
		displayName: 'Supply Date',
		name: 'supply_date',
		type: 'string',
		default: '',
		description: 'Supply or delivery date, either a date or free text depending on the type',
	},
	{
		displayName: 'Supply Date Type',
		name: 'supply_date_type',
		type: 'options',
		options: SUPPLY_DATE_TYPE_OPTIONS,
		default: 'SUPPLY_DATE',
	},
	{
		displayName: 'Template ID',
		name: 'template_id',
		type: 'string',
		default: '',
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		description: 'Title of the generated document',
	},
];

export const recurringFields: INodeProperties[] = [
	idField(resource, ['delete', 'get', 'update'], {
		description: 'ID of the recurring invoice',
	}),
	{
		displayName: 'Client ID',
		name: 'client_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: [resource],
				operation: ['create'],
			},
		},
		description: 'ID of the client the recurring invoices are issued to',
	},
	additionalFields(resource, ['create', 'update'], recurringFieldOptions),
	documentLineItemsField(resource, 'recurring invoice'),
	filterFields(resource, [
		{
			displayName: 'Client ID',
			name: 'client_id',
			type: 'string',
			default: '',
		},
		{
			displayName: 'Contact ID',
			name: 'contact_id',
			type: 'string',
			default: '',
		},
		{
			displayName: 'Cycle',
			name: 'cycle',
			type: 'options',
			options: CYCLE_OPTIONS,
			default: 'MONTHLY',
		},
		{
			displayName: 'Intro',
			name: 'intro',
			type: 'string',
			default: '',
			description: 'Free text search in the introductory text',
		},
		{
			displayName: 'Label',
			name: 'label',
			type: 'string',
			default: '',
			description: 'Free text search in the label text',
		},
		{
			displayName: 'Name',
			name: 'name',
			type: 'string',
			default: '',
			description: 'Name of the recurring',
		},
		{
			displayName: 'Note',
			name: 'note',
			type: 'string',
			default: '',
			description: 'Free text search in the explanatory notes',
		},
		{
			displayName: 'Payment Type',
			name: 'payment_type',
			type: 'multiOptions',
			options: PAYMENT_TYPE_FILTER_OPTIONS,
			default: [],
		},
		orderByField,
		tagsFilterField,
	]),
	...paginationFields(resource),
];
